name: Update Daily Video API
on:
  schedule:
    - cron: '0 8 * * *' # 每天UTC时间8:00（北京时间16:00）触发
  workflow_dispatch: # 支持手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update JSON
        run: |
          # 动态生成视频链接（日期作为文件名示例）
          TODAY=$(date +"%Y-%m-%d")
          echo '{"video_url": "https://raw.githubusercontent.com/zxs-ai/zxs-ai/main/videos/daily-video-${TODAY}.mp4"}' > api/daily-video.json

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add api/daily-video.json
          git commit -m "Update daily video API"
          git push
